# generated by datamodel-codegen:
#   filename:  invoice.schema.json

from __future__ import annotations

from datetime import date
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Party(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cnpj: Annotated[
        str,
        Field(
            description="CNPJ without punctuation: 12 alphanumeric characters plus 2 check digits",
            pattern="^[A-Z0-9]{12}[0-9]{2}$",
        ),
    ]
    name: Annotated[str, Field(description="Company name exactly as printed")]


class Invoice(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    access_key: Annotated[
        str,
        Field(
            description="44-character NF-e access key (chave de acesso), digits and uppercase letters only, no spaces",
            pattern="^[0-9]{6}[A-Z0-9]{12}[0-9]{26}$",
        ),
    ]
    number: int
    series: int
    issue_date: date
    issuer: Party
    recipient: Party
    total_amount: Annotated[str, Field(pattern="^-?[0-9]+\\.[0-9]{2}$")]
