<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Carimbo.Validation/Carimbo.Validation.csproj" />
    <ProjectReference Include="../../src/Carimbo.GroundTruth/Carimbo.GroundTruth.csproj" />
  </ItemGroup>

</Project>
