<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Carimbo.Llm/Carimbo.Llm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
